### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by lennon1997** [AMEST/DotNetCertBot#8]
Just wondering if this program is still working. I tried to run it many times both in docker and on windows however both resulted in the program ending on the line last url cloudflare login page or something to that effect.

**Comment by AMEST** [comment]
Good afternoon, the integration with cloudflare is broken. After adding the functionality in the application to work with freenom dns directly, I myself stopped using the issuance of certificates through cloudflare and therefore did not notice the problem :(

I will debug and restore the application

**Comment by lennon1997** [comment]
Okay I see that explains why I couldn’t manage to make it work no matter what I tried haha. Thank you for ur time, I look forward to using this project again once restored!
